title: CTC Business Alliance Committee
description: > # this means to ignore newlines until "baseurl:"
  The Columbia Tower Club's business alliance committee is comprised of
  experienced professionals and business owners.
  Together, we plan and host events that bring together the CTC's membership and
  the broader business community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.ctcbac.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2018_style/img/icon-large.png"

social:
  name: Tech, Brains, and Molecules
  link: "https://www.facebook.com/ColumbiaTowerClub"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ColumbiaTowerClub

# Build settings
markdown: kramdown
permalink: pretty
