title: Tech, Brains, and Molecules
description: > # this means to ignore newlines until "baseurl:"
  Tech, Brains, and Molecules brings together a cohort of highly intelligent
  and curious individuals for an intimate dinner discussion about breakthrough
  technologies and how things work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.techbrainsandmolecules.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2018_style/img/icon-large.png"

social:
  name: Tech, Brains, and Molecules
  link: "https://www.facebook.com/groups/techbrainsmolecules/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/TechBrainsAndMolecules

# Build settings
markdown: kramdown
permalink: pretty
